kind: Service
apiVersion: v1
metadata:
  name: {{.Chart.Name}}
  labels:
    app: {{.Chart.Name}}
spec:
  selector:
    app: {{.Chart.Name}}
  ports:
    - port: 9000
      name: http
      targetPort: 9000